---

#- name: Temporary set SELinux to Permissive mode
#  ansible.posix.selinux:
#    policy: targeted
#    state: permissive
#  become: true

- name: Install setools
  dnf:
    name: 
      - setroubleshoot 
      - setools
    state: present
  become: yes

- name: Copy SELinux policy module file
  copy:
    src: ../../../files/policy_inetrouter.pp
    dest: /root/policy_inetrouter.pp
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Install SELinux policy module
  shell: semodule -i /root/policy_inetrouter.pp
  become: yes

# tasks for inetrouter server provisioning

- name: Set swappiness to 20%
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '20'
    sysctl_set: yes
  become: yes

- name: Set net.core.somaxconn to 32768
  ansible.posix.sysctl:
    name: net.core.somaxconn
    value: '32768'
    sysctl_set: yes
  become: yes

- name: Enable routing 
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
  become: yes

- name: Start firewalld
  become: yes
  service:
    name: firewalld
    state: started

- name: bind interface eth0 to the public zone
  firewalld:
    interface: eth0
    state: enabled
    permanent: yes
    zone: public
  become: yes

- name: bind interface eth1 to the internal zone
  firewalld:
    interface: eth1
    state: enabled
    permanent: yes
    zone: public
  become: yes

- name: Enable HTTPS traffic
  firewalld:
    service: https
    state: enabled
    permanent: yes
  become: yes

- name: Enable TCP/8080 traffic
  firewalld:
    port: 8080/tcp
    state: enabled
    permanent: yes
  become: yes

- name: Enable Zabbix traffic
  firewalld:
    port: 10050/tcp
    state: enabled
    permanent: yes
  become: yes

- name: Enable Zabbix traffic
  firewalld:
    port: 10051/tcp
    state: enabled
    permanent: yes
  become: yes


- name: Enable traffic masquerade
  firewalld:
    masquerade: true
    state: enabled
    permanent: yes
    zone: public
  become: yes

- name: Redirect port 443 for WordPress
  firewalld:
    rich_rule: rule family=ipv4 forward-port port=443 protocol=tcp to-port=443 to-addr=192.168.57.4 
    zone: public
    permanent: yes
    state: enabled
    zone: public
  become: yes

- name: Redirect port 8080 for Zabbix
  firewalld:
    rich_rule: rule family=ipv4 forward-port port=8080 protocol=tcp to-port=8080 to-addr=192.168.57.3
    zone: public
    permanent: yes
    state: enabled
    zone: public
  become: yes

- name: Reload firewalld
  become: yes
  service:
    name: firewalld
    state: reloaded

# tasks for Zabbix agent install ------------------------------------------------------------------------------------------------

- name: Install Zabbix 6.2 repo
  become: true
  dnf:
    name: https://repo.zabbix.com/zabbix/6.2/rhel/8/x86_64/zabbix-release-6.2-1.el8.noarch.rpm
    disable_gpg_check: yes
    state: present

- name: DNF clean up
  become: true
  shell: dnf clean all


- name: Install Zabbix 6.2 agent
  become: true
  dnf:
    name:
      - zabbix-agent
    disable_gpg_check: yes
    state: present

- name: Change Zabbix server address
  replace:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: 'Server=127.0.0.1'
    replace: 'Server=192.168.57.3'
  become: yes

- name: Change Zabbix active server address
  replace:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: 'ServerActive=127.0.0.1'
    replace: 'ServerActive=192.168.57.3'
  become: yes

- name: Change Zabbix agent hostname
  replace:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: 'Hostname=Zabbix server'
    replace: 'Hostname=inetrouter'
  become: yes

- name: Reload zabbix_agentd
  become: yes
  service:
    name: zabbix-agent
    enabled: yes
    state: restarted

# tasks for rsyslog install ------------------------------------------------------------------------------------------------

- name: Install rsyslog
  dnf:
    name: rsyslog
    state: present
  become: yes

- name: Relay syslog critical & error messages to monlog server
  template: "src=../templates/crit.conf dest=/etc/rsyslog.d/crit.conf owner=root group=root mode=0644"
  become: yes

- name: Relay audit log messages to monlog server
  template: "src=../templates/audit.conf dest=/etc/rsyslog.d/audit.conf owner=root group=root mode=0644"
  become: yes

- name: Restart rsyslog
  become: yes
  service:
    name: rsyslog
    enabled: yes
    state: restarted
