---
- name: Temporary set SELinux to Permissive mode
  ansible.posix.selinux:
    policy: targeted
    state: permissive
  become: true

# tasks for SELinux configuration -----------------------------------------------------------------------------------------

- name: Install python3-libsemanage
  dnf:
    name: python3-libsemanage
    state: present
  become: yes

#- name: Copy SELinux policy module file
#  copy:
#    src: ../../../files/policy_backup.pp
#    dest: /root/policy_backup.pp
#    owner: root
#    group: root
#    mode: '0644'
#  become: yes

#- name: Install SELinux policy module
#  shell: semodule -i /root/policy_backup.pp
#  become: yes

- name: Enable Zabbix traffic
  firewalld:
    port: 10050/tcp
    state: enabled
    permanent: yes
  become: yes

- name: Enable Zabbix traffic
  firewalld:
    port: 10051/tcp
    state: enabled
    permanent: yes
  become: yes

- name: Reload firewalld
  become: yes
  service:
    name: firewalld
    state: reloaded

# tasks for Zabbix agent install ------------------------------------------------------------------------------------------------

- name: Install Zabbix 6.2 repo
  become: true
  dnf:
    name: https://repo.zabbix.com/zabbix/6.2/rhel/8/x86_64/zabbix-release-6.2-1.el8.noarch.rpm
    disable_gpg_check: yes
    state: present

- name: DNF clean up
  become: true
  shell: dnf clean all


- name: Install Zabbix 6.2 agent
  become: true
  dnf:
    name:
      - zabbix-agent
    disable_gpg_check: yes
    state: present

- name: Change Zabbix server address
  replace:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: 'Server=127.0.0.1'
    replace: 'Server=192.168.57.3'
  become: yes

- name: Change Zabbix active server address
  replace:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: 'ServerActive=127.0.0.1'
    replace: 'ServerActive=192.168.57.3'
  become: yes

- name: Change Zabbix agent hostname
  replace:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: 'Hostname=Zabbix server'
    replace: 'Hostname=backup'
  become: yes

- name: Reload zabbix_agentd
  become: yes
  service:
    name: zabbix-agent
    state: restarted

# tasks for BorgBackup install ------------------------------------------------------------------------------------------------

- name: Download BorgBackup
  uri:
    url: https://github.com/borgbackup/borg/releases/download/1.2.2/borg-linux64
    dest: /root/borg-linux64
    status_code: 200, 302, 304
    mode: 'u=rwx,g=rwx,o=rx'
  become: yes

- name: Create user borg
  user:
    name: borg
    state: present
  become: yes

#- name: Copy private SSH key
#  copy: content="{{ private_SSH_key }}" dest=/path/to/destination/file

# tasks for rsyslog install ------------------------------------------------------------------------------------------------

- name: Install rsyslog
  dnf:
    name: rsyslog
    state: present
  become: yes

- name: Relay syslog critical & error messages to monlog server
  template: "src=../templates/crit.conf dest=/etc/rsyslog.d/crit.conf owner=root group=root mode=0644"
  become: yes

- name: Relay audit log messages to monlog server
  template: "src=../templates/audit.conf dest=/etc/rsyslog.d/audit.conf owner=root group=root mode=0644"
  become: yes

- name: Restart rsyslog
  become: yes
  service:
    name: rsyslog
    state: restarted
