# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
config.vm.network :forwarded_port, guest:22, host: 2255, id: "ssh", auto_correct: true
    v.memory = 256
    v.cpus = 1
  end
  
  config.vm.define "psax" do |psax|
    psax.vm.hostname = "psax"
    psax.vm.provision "file", source: "psax.sh", destination: "psax.sh"
  end
end
