# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end
  config.vm.define "pamc" do |pamc|
    pamc.vm.provision "shell", path: "pam.sh"
    pamc.vm.hostname = "pamc"
  end
end
