- hosts: monlog

  roles:
    - role: monlog
      tags: monlog

- hosts: inetrouter

  roles:
    - role: inetrouter
      tags: inetrouter

- hosts: backup

  roles:
    - role: backup
      tags: backup

- hosts: wordpress

  roles:
    - role: wordpress
      tags: wordpress
