# -*- mode: ruby -*-
# vi: set ft=ruby :
# export VAGRANT_EXPERIMENTAL="disks"

Vagrant.configure("2") do |config|

config.vm.define "server" do |server|
  server.vm.box = 'centos/8.4'
  server.vm.host_name = 'server'
  server.vm.network :private_network, ip: "10.0.1.10"
  server.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

end
